on:
  pull_request_target:

jobs:
  a:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - run: echo ${{ github.event.pull_request.head.ref }}
